### ISSUE TITLE
Can't use yaxis labels formatter

### ISSUE THREAD

**Issue by haniefhan** [onmotion/yii2-widget-apexcharts#17]
Hello there, 
This is my chart and script in yii
`<?php`
`  echo ApexchartsWidget::widget([`
`    'type' => 'line',`
`    'height' => 450,`
`    'chartOptions' =>[`
`      'title' => ['text' => $this->title],`
`      'yaxis' => [`
`        'title' => [`
`          'text' => 'Rp'`
`        ],`
`        'min' => 0,`
`        'max' => 30000000000,`
`        'tickAmount' => 6,`
`        'labels' => [`
`          'show' => true,`
`          // 'formatter' => function ($val, $index){`
`          //   return ($val / 1000000000). 'B';`
`          // }`
`        ]`
`      ],`
`      'xaxis' => [`
`        'title' => [`
`          'text' => 'Bulan'`
`        ],`
`        'categories' => $bulan,`
`      ],`
`      'markers' => [`
`        'size'=> 4,`
`        'strokeWidth' => 0,`
`        'hover' => [`
`          'size' => 6`
`        ]`
`      ],`
`      'grid' => [`
`        'borderColor' => '#e7e7e7',`
`        'row' => [`
`          'colors' => ['#f3f3f3', 'transparent'],`
`          'opacity' => 0.5`
`        ],`
`      ],`
`      'stroke' => [`
`        'width' => 3`
`      ]`
`    ],`
`    'series' => $series`
`  ]);`
`?>`

![ohim8oan](https://user-images.githubusercontent.com/10968783/99341580-c04a7580-28bc-11eb-8764-4d82b892df9f.png)

I want to make the labels on yaxis use billion (B) code than full number (3.000.000.000 -> 3 B). 
How can I do that?

I use formatter (uncomment the yaxis.labels.formmatter), but returned blank chart.

![blank](https://user-images.githubusercontent.com/10968783/99341820-2df6a180-28bd-11eb-890c-0cb3adecf695.PNG)

Can you help me?

**Comment by onmotion** [comment]
Hi. 

I think this problem related not for Yii widget, but for apexcharts itself. Try take a look to the official docs https://apexcharts.com/docs/options/labels/
Also look in the console it might be helpful.

**Comment by haniefhan** [comment]
Hmm..
I want to use this options :
yaxis.labels.formatter
[https://apexcharts.com/docs/options/yaxis/](https://apexcharts.com/docs/options/yaxis/)

How to use this "formatter" in this plugin? Do you have some example maybe?

I will really appreciated any help

**Comment by onmotion** [comment]
```php
$series = [
    [
        'name' => 'Entity 1',
        'data' => [10, 20, 50, 80],
    ],
    [
        'name' => 'Entity 2',
        'data' => [22, 20, 44, 80],
    ],
    [
        'name' => 'Entity 3',
        'data' => [10, 65, 50, 88],
    ],
    [
        'name' => 'Entity 4',
        'data' => [10, 30, 50, 100],
    ],
];

echo \onmotion\apexcharts\ApexchartsWidget::widget([
    'type' => 'line', // default area
    'height' => '400', // default 350
    'width' => '500', // default 100%
    'chartOptions' => [
        'chart' => [
            'toolbar' => [
                'show' => true,
                'autoSelected' => 'zoom'
            ],
        ],
        'xaxis' => [
            'labels' => ['show' => true]
        ],
        'yaxis' => [
            'show' => true,
            'labels' => ['show' => true, 'align' => 'right',
                'axisBorder' => [
                    'show' => true,
                    'color' => '#78909C',
                    'offsetX' => 0,
                    'offsetY' => 0
                ]
            ],
            'title' => [
                'text' => 'example',
                'rotate' => -80
            ]
        ],
        'dataLabels' => [
            'enabled' => false
        ],
    ],
    'series' => $series,
]);
```

![image](https://user-images.githubusercontent.com/12899080/99766510-4a3f4c00-2b12-11eb-931a-3525695ff71d.png)

**Comment by haniefhan** [comment]
thanks for your example.
How about if I want to make yaxis showed like this?
$ 100.00
$ 80.00
$ 60.00
$ 40.00
$ 20.00
$ 0.00

**Comment by iglooom** [comment]
Hi guys, got the same issue and found workaround. Hope it helps you.
`'yaxis' => [
    'labels' => [
        'formatter' => new \yii\web\JsExpression('function(data) { return data+"%"; }'),
    ]
]`
