### ISSUE TITLE
Chart not swowing in yii\bootstrap\Tabs and yii\bootstrap\Collapse

### ISSUE THREAD

**Issue by Artkoha** [onmotion/yii2-widget-apexcharts#3]
Hi!
If i put chart widget into bootstrap tabs or bootstrap collapse it's not showing in not active tabs. When i open browser console it is showing however..

**Comment by onmotion** [comment]
Hi

I don't know, in my case it works fine:

```php
echo \yii\bootstrap\Collapse::widget([
            'items' => [
                [
                    'label' => 'Tab 1',
                    'content' => \onmotion\apexcharts\ApexchartsWidget::widget([
                        'type' => 'bar', // default area
                        'height' => '400', // default 350
                        'width' => '500', // default 100%
                        'chartOptions' => [
                            'chart' => [
                                'toolbar' => [
                                    'show' => true,
                                    'autoSelected' => 'zoom'
                                ],
                            ],
                            'xaxis' => [
                                'type' => 'datetime',
                                // 'categories' => $categories,
                            ],
                            'plotOptions' => [
                                'bar' => [
                                    'horizontal' => false,
                                    'endingShape' => 'rounded'
                                ],
                            ],
                            'dataLabels' => [
                                'enabled' => false
                            ],
                            'stroke' => [
                                'show' => true,
                                'colors' => ['transparent']
                            ],
                            'legend' => [
                                'verticalAlign' => 'bottom',
                                'horizontalAlign' => 'left',
                            ],
                        ],
                        'series' => $series
                    ]),
                    'contentOptions' => [
                        'class' => 'in'
                    ],
                    'options' => [],
                    //'encodeLabels' => false,
                ],
                [
                    'label' => 'Tab 2',
                    'content' => \onmotion\apexcharts\ApexchartsWidget::widget([
                        'type' => 'area', // default area
                        'height' => '300', // default 350
                        'width' => '400', // default 100%
                        'chartOptions' => [
                            'chart' => [
                                'toolbar' => [
                                    'show' => true,
                                    'autoSelected' => 'zoom'
                                ],
                            ],
                            'xaxis' => [
                                'type' => 'datetime',
                                // 'categories' => $categories,
                            ],
                            'plotOptions' => [
                                'bar' => [
                                    'horizontal' => false,
                                    'endingShape' => 'rounded'
                                ],
                            ],
                            'dataLabels' => [
                                'enabled' => false
                            ],
                            'stroke' => [
                                'show' => true,
                                'colors' => ['transparent']
                            ],
                            'legend' => [
                                'verticalAlign' => 'bottom',
                                'horizontalAlign' => 'left',
                            ],
                        ],
                        'series' => $series
                    ]),
                ],
            ]
        ]);
```

![2019-05-06_09-51-24](https://user-images.githubusercontent.com/12899080/57210295-d186a680-6fe4-11e9-836a-db9f98db1a2f.png)

![2019-05-06_09-51-38](https://user-images.githubusercontent.com/12899080/57210303-d64b5a80-6fe4-11e9-9c64-c5c74225cc79.png)

**Comment by Artkoha** [comment]
> Hi
> 
> I don't know, in my case it works fine:
> 
> ```
> echo \yii\bootstrap\Collapse::widget([
>             'items' => [
>                 [
>                     'label' => 'Tab 1',
>                     'content' => \onmotion\apexcharts\ApexchartsWidget::widget([
>                         'type' => 'bar', // default area
>                         'height' => '400', // default 350
>                         'width' => '500', // default 100%
>                         'chartOptions' => [
>                             'chart' => [
>                                 'toolbar' => [
>                                     'show' => true,
>                                     'autoSelected' => 'zoom'
>                                 ],
>                             ],
>                             'xaxis' => [
>                                 'type' => 'datetime',
>                                 // 'categories' => $categories,
>                             ],
>                             'plotOptions' => [
>                                 'bar' => [
>                                     'horizontal' => false,
>                                     'endingShape' => 'rounded'
>                                 ],
>                             ],
>                             'dataLabels' => [
>                                 'enabled' => false
>                             ],
>                             'stroke' => [
>                                 'show' => true,
>                                 'colors' => ['transparent']
>                             ],
>                             'legend' => [
>                                 'verticalAlign' => 'bottom',
>                                 'horizontalAlign' => 'left',
>                             ],
>                         ],
>                         'series' => $series
>                     ]),
>                     'contentOptions' => [
>                         'class' => 'in'
>                     ],
>                     'options' => [],
>                     //'encodeLabels' => false,
>                 ],
>                 [
>                     'label' => 'Tab 2',
>                     'content' => \onmotion\apexcharts\ApexchartsWidget::widget([
>                         'type' => 'area', // default area
>                         'height' => '300', // default 350
>                         'width' => '400', // default 100%
>                         'chartOptions' => [
>                             'chart' => [
>                                 'toolbar' => [
>                                     'show' => true,
>                                     'autoSelected' => 'zoom'
>                                 ],
>                             ],
>                             'xaxis' => [
>                                 'type' => 'datetime',
>                                 // 'categories' => $categories,
>                             ],
>                             'plotOptions' => [
>                                 'bar' => [
>                                     'horizontal' => false,
>                                     'endingShape' => 'rounded'
>                                 ],
>                             ],
>                             'dataLabels' => [
>                                 'enabled' => false
>                             ],
>                             'stroke' => [
>                                 'show' => true,
>                                 'colors' => ['transparent']
>                             ],
>                             'legend' => [
>                                 'verticalAlign' => 'bottom',
>                                 'horizontalAlign' => 'left',
>                             ],
>                         ],
>                         'series' => $series
>                     ]),
>                 ],
>             ]
>         ]);
> ```
> 
> ![2019-05-06_09-51-24](https://user-images.githubusercontent.com/12899080/57210295-d186a680-6fe4-11e9-836a-db9f98db1a2f.png)
> 
> ![2019-05-06_09-51-38](https://user-images.githubusercontent.com/12899080/57210303-d64b5a80-6fe4-11e9-9c64-c5c74225cc79.png)

Thank you!
Recently i found this css code that solve problem with tabs and collapse

```
.tab-content>.tab-pane {
    display: block;
    height: 0;
    overflow: hidden;
}
.tab-content>.tab-pane.active {
    height: auto;
}
```

**Comment by onmotion** [comment]
Ok. Also update the widget, it has been upgraded to the new version apexcharts.
