### ISSUE TITLE
Update to latest apexcharts version

### ISSUE THREAD

**Issue by Mixali4** [onmotion/yii2-widget-apexcharts#30]
There are some known issues in version of apexcharts.js, used by widget at this moment.
Could you update it to latest?

**Comment by raimon-segura** [comment]
Hi!,

Executing `npm install apexcharts --save` and then `npm run build` in `yii2-widget-apexcharts/assets/` directory will update package versions, from `3.22.0` to `3.36.3` .

I noticed that `3.36.3` version show less warning in chrome console and it runs quite fast... hope it helps to update this great yii2 extension.

Thanks!

**Comment by Mixali4** [comment]
@raimon-segura, thank you very much! Worked.

**Comment by raimon-segura** [comment]
can be updated the extension "yii2-widget-apexcharts" itself @onmotion ? ...so, we can avoid modifiying things after composer install

Many Thanks!

**Comment by onmotion** [comment]
Hi guys! I've update apexcharts version but not sure if it will work 'cause I don't use yii2 and php itself for a long time

Have a great day!
