### ISSUE TITLE
Update JS library!

### ISSUE THREAD

**Issue by raimon-segura** [onmotion/yii2-widget-apexcharts#39]
Hi all!,

Related to this bug https://github.com/onmotion/yii2-widget-apexcharts/issues/30 ...it could be great to update apex JS library from 3.22.0 to 3.36.3 ..because it fixes a lot of issues and it goes much faster.

Many thanks!

**Comment by raimon-segura** [comment]
any update @onmotion !? ..do you need more info? :smiley_cat: 

thanks!

**Comment by onmotion** [comment]
I see apexcharts version `3.37.0` in the build https://github.com/onmotion/yii2-widget-apexcharts/blob/master/assets/dist/build.js

**Comment by raimon-segura** [comment]
OHH!.. you are right, so it might a issue in my composer update.. many thanks for your quick reply! :smiley:
